version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      network:
        ipv4_address: 172.20.0.50

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sd.org
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      network:
        ipv4_address: 172.20.0.51
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    networks:
      network:
        ipv4_address: 172.20.0.52

volumes:
  db-data:
  pgadmin-data:
  redis-data:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

